[package]
authors = ["Adam <adamsimeth@gmail.com>"]
name = "admiral"
version = "1.1.0"

[dependencies]
clap = "2.29.2"
serde = "1.0.27"
serde_derive = "1.0.27"
threadpool = "1.7.1"
toml = "0.4.5"
chan = "0.1.20"
chan-signal = "0.3.1"
